### ISSUE TITLE
Embedding Matrix doesn't maintain order of entries

### ISSUE THREAD

**Issue by zetterlund** [WillKoehrsen/recurrent-neural-networks#5]
I should first say thanks for writing such an awesome walkthrough.

I wanted to let you know that I encountered a problem when replicating your code in the "Deep Dive into Recurrent Neural Networks" notebook.

At "In [28]": `for i, word in enumerate(word_idx.keys())`

However, enumerating over a dictionary's keys doesn't maintain the order of the entries, so the embedding matrix isn't mapped properly to the `word_idx` dictionary.

To get it to work, I changed it to `for word, i in word_idx.items():` and then also changed the line in the `for` loop to: `embedding_matrix[i, :] = vector`

I don't know if it's because I'm using a different version of Python, or why this discrepancy exists. 
 I hope this helps anyone else who was stuck like I was.

**Comment by WillKoehrsen** [comment]
Dictionaries are insertion ordered in Python 3.6+. This means that iterating through the items will be done in the same order they were entered. I used Python 3.6 for this project, thus ensuring the correct ordering of the dictionary keys. 

https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6/39980744
