### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by bbartling** [WillKoehrsen/recurrent-neural-networks#6]
Hi Will,

Could this project be accomplished without docker? At a beginner novice level I am familiar with flask and keras but why is docker required if I can install Tensorflow/keras on my windows PC thru anaconda py 3.7

Thanks,
Ben

**Comment by WillKoehrsen** [comment]
Yes, you should be able to complete this project without docker by installing the libraries in [`requirements.txt`](https://github.com/WillKoehrsen/recurrent-neural-networks/blob/master/requirements.txt). Docker allows for easier-to-reproduce environments across operating systems.
